#! /bin/sh
set -e

case "$(uname -s)" in
   Darwin)
     SCRIPT_PATH=$(greadlink -f "$0")
     ;;

   *)
     SCRIPT_PATH=$(readlink -f "$0")
     ;;
esac

PROJECT_DIR=$(dirname "$SCRIPT_PATH")

cd "$PROJECT_DIR"

totalMemKB=$(free --kilo |awk '/^Mem:/{print $4}')

# Percentage of free memory to use for Java
usageFactor=80

# Percentage to use for the heap
heapFactor=80

# heap size in KB
avKB=$(($totalMemKB*$usageFactor/100))

# heap size in MB
heapMB=$(($avKB*$heapFactor/1024/100))

stackMB=$((($avKB / 1024 - $heapMB)))


dist/graalvm/bin/native-image --no-fallback -R:MaxHeapSize=$(($heapMB))m -cp target/nildumu-minimal-jar-with-dependencies.jar:target/native-image nildumu.Main -H:Name=eval-programs/nildumu
