#!/usr/bin/env sh
set -e

case "$(uname -s)" in
   Darwin)
     SCRIPT_PATH=$(greadlink -f "$0")
     ;;

   *)
     SCRIPT_PATH=$(readlink -f "$0")
     ;;
esac

PROJECT_DIR=$(dirname "$SCRIPT_PATH")

cd "$PROJECT_DIR"
./download_solvers
mvn compile > /dev/null
mvn exec:java -Dcmd -q -Dexec.args="$*"

